---
- name: Ensure service group exists
  group:
    name: "{{ tm_user }}"
    state: present
- name: Ensure service user exists
  user:
    name: "{{ tm_user }}"
    group: "{{ tm_user }}"
    home: /home/tendermint
    state: present
- name: Deploy service definition to nodes
  template:
    src: templates/tendermint.service.jinja2
    dest: /etc/systemd/system/tendermint.service
- name: Reload systemd services
  systemd:
    daemon_reload: yes
